"pg_get_triggerdef"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tpgfundledger AFTER INSERT ON public.pg_trn_tpgfundledger FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tpgfundledger()"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tpgmemberledger AFTER INSERT ON public.pg_trn_tpgmemberledger FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tpgmemberledger()"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tprocure AFTER INSERT ON public.pg_trn_tprocure FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tprocure()"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tprocureproduct AFTER INSERT ON public.pg_trn_tprocureproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tprocureproduct()"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tprocurestockbydate AFTER INSERT ON public.pg_trn_tprocureproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tprocurestockbydate()"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tsaleproduct AFTER INSERT ON public.pg_trn_tsaleproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tsaleproduct()"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tsalestockbydate AFTER INSERT ON public.pg_trn_tsaleproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tsalestockbydate()"
"CREATE TRIGGER trg_aft_cxx_pg_trn_tsession AFTER INSERT ON public.pg_trn_tsession FOR EACH ROW EXECUTE FUNCTION fn_aft_cxx_pg_trn_tsession()"
"CREATE TRIGGER trg_aft_dxx_pg_trn_tpgfundledger AFTER DELETE ON public.pg_trn_tpgfundledger FOR EACH ROW EXECUTE FUNCTION fn_aft_dxx_pg_trn_tpgfundledger()"
"CREATE TRIGGER trg_aft_dxx_pg_trn_tpgmemberledger AFTER DELETE ON public.pg_trn_tpgmemberledger FOR EACH ROW EXECUTE FUNCTION fn_aft_dxx_pg_trn_tpgmemberledger()"
"CREATE TRIGGER trg_aft_dxx_pg_trn_tprocure AFTER DELETE ON public.pg_trn_tprocure FOR EACH ROW EXECUTE FUNCTION fn_aft_dxx_pg_trn_tprocure()"
"CREATE TRIGGER trg_aft_dxx_pg_trn_tprocureproduct AFTER DELETE ON public.pg_trn_tprocureproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_dxx_pg_trn_tprocureproduct()"
"CREATE TRIGGER trg_aft_dxx_pg_trn_tprocurestockbydate AFTER DELETE ON public.pg_trn_tprocureproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_dxx_pg_trn_tprocurestockbydate()"
"CREATE TRIGGER trg_aft_dxx_pg_trn_tsaleproduct AFTER DELETE ON public.pg_trn_tsaleproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_dxx_pg_trn_tsaleproduct()"
"CREATE TRIGGER trg_aft_dxx_pg_trn_tsalestockbydate AFTER DELETE ON public.pg_trn_tsaleproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_dxx_pg_trn_tsalestockbydate()"
"CREATE TRIGGER trg_aft_insupdt_pg_mst_tpgmember AFTER INSERT OR UPDATE ON public.pg_mst_tpgmember FOR EACH ROW EXECUTE FUNCTION aft_insupdt_pg_mst_tpgmember()"
"CREATE TRIGGER trg_aft_uxx_pg_trn_tpgfundledger AFTER UPDATE ON public.pg_trn_tpgfundledger FOR EACH ROW WHEN ((new.* IS DISTINCT FROM old.*)) EXECUTE FUNCTION fn_aft_uxx_pg_trn_tpgfundledger()"
"CREATE TRIGGER trg_aft_uxx_pg_trn_tpgmemberledger AFTER UPDATE ON public.pg_trn_tpgmemberledger FOR EACH ROW WHEN ((new.* IS DISTINCT FROM old.*)) EXECUTE FUNCTION fn_aft_uxx_pg_trn_tpgmemberledger()"
"CREATE TRIGGER trg_aft_uxx_pg_trn_tprocure AFTER UPDATE ON public.pg_trn_tprocure FOR EACH ROW WHEN ((new.* IS DISTINCT FROM old.*)) EXECUTE FUNCTION fn_aft_uxx_pg_trn_tprocure()"
"CREATE TRIGGER trg_aft_uxx_pg_trn_tprocureproduct AFTER UPDATE ON public.pg_trn_tprocureproduct FOR EACH ROW WHEN ((new.* IS DISTINCT FROM old.*)) EXECUTE FUNCTION fn_aft_uxx_pg_trn_tprocureproduct()"
"CREATE TRIGGER trg_aft_uxx_pg_trn_tprocurestockbydate AFTER UPDATE ON public.pg_trn_tprocureproduct FOR EACH ROW WHEN ((new.* IS DISTINCT FROM old.*)) EXECUTE FUNCTION fn_aft_uxx_pg_trn_tprocurestockbydate()"
"CREATE TRIGGER trg_aft_uxx_pg_trn_tsaleproduct AFTER UPDATE ON public.pg_trn_tsaleproduct FOR EACH ROW WHEN ((new.* IS DISTINCT FROM old.*)) EXECUTE FUNCTION fn_aft_uxx_pg_trn_tsaleproduct()"
"CREATE TRIGGER trg_aft_uxx_pg_trn_tsalestockbydate AFTER UPDATE ON public.pg_trn_tsaleproduct FOR EACH ROW EXECUTE FUNCTION fn_aft_uxx_pg_trn_tsalestockbydate()"
"CREATE TRIGGER trg_bef_cxx_pg_mst_tpgmember BEFORE INSERT ON public.pg_mst_tpgmember FOR EACH ROW EXECUTE FUNCTION fn_bef_cxx_pg_mst_tpgmember()"
"CREATE TRIGGER trg_bef_uxx_pg_trn_tpgfundledger BEFORE UPDATE ON public.pg_trn_tpgfundledger FOR EACH ROW WHEN ((new.* IS DISTINCT FROM old.*)) EXECUTE FUNCTION fn_bef_uxx_pg_trn_tpgfundledger()"
